### ISSUE TITLE
Plugin must be force quit

### ISSUE THREAD

**Issue by rapamatic** [FlyingDiver/Indigo-radiora2#12]
I believe I've seen this error for a while (before the betas), but I've just ignored it. With all the testing I've seen it enough to point it out. I don't know what is causing this - could either be just something in the shutdown handling code, or could be that the monitoring code is hanging on something (but I don't see any evidence of that)...

```
Mar 20, 2018, 10:40:56 AM
   Reloading plugin "Lutron RRA2/Caséta 7.1.1"
   Stopping plugin "Lutron RRA2/Caséta 7.1.1" (pid 29531)

Mar 20, 2018, 10:41:11 AM
   Error                           process (pid 29531) failed to quit after polite request -- forcing it to quit now
   Stopped plugin "Lutron RRA2/Caséta 7.1.1"
   Starting plugin "Lutron RRA2/Caséta 7.1.1" (pid 29581)
   Started plugin "Lutron RRA2/Caséta 7.1.1"

```

**Comment by FlyingDiver** [comment]
Yeah, I keep seeing that too.  It's on my list to look into, but good to have an issue open too.

**Comment by FlyingDiver** [comment]
Seems to happen more often when debug logging, so I removed all the debug statements from deviceStopComm (and deviceStartComm).  Maybe it was just taking too long to log all that info.  Have to see if that takes care of it.

**Comment by FlyingDiver** [comment]
Not fixed.  :(

**Comment by FlyingDiver** [comment]
Pretty sure I found the issue. Will be in next release (after 7.1.0-b6)
