### ISSUE TITLE
Data needed for Caséta systems

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/Indigo-radiora2#17]
Looking for examples of the JSON data from a Caséta smart bridge pro.

**Comment by agmww** [comment]
Is this what your looking for?
[Lutron Integration Report.zip](https://github.com/FlyingDiver/Indigo-radiora2/files/1868261/Lutron.Integration.Report.zip)

**Comment by FlyingDiver** [comment]
Yes, exactly.  Thank you.

**Comment by FlyingDiver** [comment]
Looking at that file, it appears you have 11 Pico type keypads and 24 loads (switches/dimmers).  Is that correct?

**Comment by agmww** [comment]
Yes that is correct.

**Comment by FlyingDiver** [comment]
Excellent.  What's the URL for fetching that from the Smart Bridge?  Does it require a login?

**Comment by agmww** [comment]
I’m not sure what you are asking.  All programming I have done for the for Caseta has been done through either my iPhone or iPad and does require a login.

**Comment by FlyingDiver** [comment]
How did you get that file?  Saved from the iOS app?

**Comment by agmww** [comment]
Yes, the iOS app, under the advanced option in settings. The app calls it a Integration Report.

**Comment by FlyingDiver** [comment]
Have you ever tried opening a browser window with the address of the smart bridge?  Does it have an HTTP server like the RRA2 repeaters do?  Can you try it and tell me what happens?

I'm trying to figure out if the plugin can get the data from the bridge directly, without having to require the user to download that file first.

**Comment by agmww** [comment]
Never thought to try but does not appear to.

**Comment by agmww** [comment]
Sorry, does not appear to have a HTTP Server.

**Comment by FlyingDiver** [comment]
Bummer.  So we'll have to go the read data from file route.  Is "Lutron Integration Report" the default name for the file as downloaded from the app?

**Comment by agmww** [comment]
When you choose the option in the iOS app, it emails the report.  It's not an actual file.  I copied and pasted the email to a text file.

**Comment by FlyingDiver** [comment]
Got it.  Hmm.  I wonder if I can open a dialog box and you could paste the data into that.  Worth a try.

**Comment by agmww** [comment]
Sorry, not sure what you asking.

**Comment by FlyingDiver** [comment]
Just thinking out loud.  ;)

**Comment by agmww** [comment]
Oh, I understand now.  Would you like me to forward the email the email it sends.

**Comment by FlyingDiver** [comment]
No, that's not necessary.  I'll use the file you sent for testing.

**Comment by FlyingDiver** [comment]
I think I have what I need.  If anyone else wants to share data for testing purposes, please do so.
