### ISSUE TITLE
Enable all fan speeds

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/Indigo-radiora2#20]
If Indigo can handle it.  Checking now.

**Comment by rapamatic** [comment]
From what I recall when I worked on this code, you’d need to basically create a custom device type, and lose all the built in fan GUIs and controls... this was back in Indigo 6, so maybe this changed with 7, but I doubt it

**Comment by FlyingDiver** [comment]
Well, if the GUI can't do it as a standard device, I can always add a custom action to set it to the other speeds.

**Comment by FlyingDiver** [comment]
Added actions to set the specific Lutron speeds, independent of the Indigo UI.
