### ISSUE TITLE
Auto-create does not work with RRA2 Select repeater

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/Indigo-radiora2#22]

**Comment by link266** [comment]
Integration report requested... uploading here.

[Michael Zoradi - Lutron Radio RA2 Select Integration Report - 2018-05-03.zip](https://github.com/FlyingDiver/Indigo-radiora2/files/1982230/Michael.Zoradi.-.Lutron.Radio.RA2.Select.Integration.Report.-.2018-05-03.zip)

**Comment by FlyingDiver** [comment]
Appears to work properly using Caséta process.  Updated the Wiki to match.
