### ISSUE TITLE
Fan error in log

### ISSUE THREAD

**Issue by gt3mike** [FlyingDiver/Indigo-radiora2#25]
I have a couple of fans that are being controlled with RRD-2ANF fan controls. When I tap the controls on the wall, I get this error in the log:

   Error                           device "Kitchen - Fan 19 - Office Fan" state key ActualSpeed not defined (ignoring update request)

Not sure if this was introduced with 7.2 or if it existed before.

I'm running Indigo 7 with the 7.2.0. Lutron plugin. My Lutron system is a full RadioRA 2 system with a main repeater (not Select).

**Comment by FlyingDiver** [comment]
Try editing the Fan devices.  Just open up the edit device dialog, then save it.

**Comment by gt3mike** [comment]
That fixed it. Strange, as the plugin created those devices. But perhaps it was a beta that created them.
