### ISSUE TITLE
Caseta Problems

### ISSUE THREAD

**Issue by VeniceNerd** [FlyingDiver/Indigo-radiora2#26]
Hi!

I have the Lutron Caseta Bridge to control 4 shades in my home. The Lutron bridge is connected via Ethernet to my Network switch with a static IP. However, I can't get this plugin to work in Indigo. Here is my settings page:

![screen shot 2018-07-25 at 7 07 45 pm](https://user-images.githubusercontent.com/25128243/43237407-87f6abfe-903e-11e8-8a3c-7a2a28af9889.png)

And here is the error log:
![screen shot 2018-07-25 at 7 08 18 pm](https://user-images.githubusercontent.com/25128243/43237410-8f23fc74-903e-11e8-9141-b501b4af3b56.png)

Any idea why the devices are not showing up? Did I configure the plugin incorrectly?

**Comment by FlyingDiver** [comment]
Which bridge do you have, exactly?  The plugin requires the "Caséta Smart Bridge Pro" to work.

**Comment by VeniceNerd** [comment]
Oh snap. Yeah I don’t have the Pro. Just the regular Caseta. :(

**Comment by FlyingDiver** [comment]
I need to update the docs to clarify that.  It says so on the Wiki page for device auto-creation, but not on the ReadMe.
