### ISSUE TITLE
Shouldn't turn on light & set brightness

### ISSUE THREAD

**Issue by rapamatic** [FlyingDiver/Indigo-radiora2#27]
Per my discussions here https://forums.indigodomo.com/viewtopic.php?f=78&t=17432&p=170975 when a light is turned on the plugin should not be turning the device on and then separately setting the brightness of the device. Instead, it should just be setting the brightness.

The fix is just to remove the first update statement that sets the ONOFF state to true, leaving just the statement setting the brightness level.

At least in the plugin version running on my mac, this code starts on line 863, and the line to remove is line 867:

```
zone = self.dimmers[id]
                if int(level) == 0:
                    zone.updateStateOnServer(ONOFF, False)
                else:
                    zone.updateStateOnServer(ONOFF, True)
                    zone.updateStateOnServer("brightnessLevel", int(level))
                self.logger.debug(u"Received: Dimmer " + zone.name + " level set to " + str(level))

```
should instead be:

```
zone = self.dimmers[id]
                if int(level) == 0:
                    zone.updateStateOnServer(ONOFF, False)
                else:
                    zone.updateStateOnServer("brightnessLevel", int(level))
                self.logger.debug(u"Received: Dimmer " + zone.name + " level set to " + str(level))
```

I don't know if this is the same thing for other device types (fans perhaps, shades unlikely)

**Comment by FlyingDiver** [comment]
Will look at this when I get home again, which won’t be until Christmas. 

joe

**Comment by rapamatic** [comment]
Enjoy the diving! I made the change in my local copy of the plugin and it’s working fine.

**Comment by FlyingDiver** [comment]
You could fork the repo and do a pull request.  :)

**Comment by rapamatic** [comment]
I’ll give it a shot. I usually manage to screw up github somehow.

**Comment by gt3mike** [comment]
What incorrect lighting behavior does this fix? Just curious - I’ve never
noticed a problem.

**Comment by rapamatic** [comment]
It’s a very bizarre edge case. The old code would first turn the light device on, and which point it would show its default brightness (100%). Almost immediately thereafter the code would update the device to the correct brightness. Normally this wouldn’t be an issue, since the device in indigo would only show the incorrect 100% brightness for a split second. However, I had triggers based on lights going to 100%, and they were being falsely triggered by that split second 100% brightness. This change prevents that from happening.

**Comment by rapamatic** [comment]
> You could fork the repo and do a pull request. :)

Alright, just submitted the pull request

**Comment by FlyingDiver** [comment]
Releasing in 7.2.3
