### ISSUE TITLE
Lutron Homework QS Support

### ISSUE THREAD

**Issue by markaslett** [FlyingDiver/Indigo-radiora2#35]
Flyingdiver, does the plugin currently support Homework QS? Many thanks, Mark

**Comment by FlyingDiver** [comment]
That's a good question.  It's never been tested with QS, that I know of.  But according to the Integration Protocol document I have, most of the commands that the plugin uses are the same.  So for basic functionality, it probably will work.  

There's no support for some of the more advanced things that the QS system does, like button hold or multiple-tap, or devices that aren't available to RRa2.

However, if the basic communication and control works, and you need support added for additional commands or devices, I can certainly add them.  You'll have to do all the testing.

**Comment by FlyingDiver** [comment]
Here's the document that the plugin is based on.

[Lutron Integration Protocol 2017-08-29.pdf](https://github.com/FlyingDiver/Indigo-radiora2/files/3390015/Lutron.Integration.Protocol.2017-08-29.pdf)

**Comment by FlyingDiver** [comment]
Oh look, a newer one.  ;)
[Lutron Integration Protocol AA 2019-03-12.pdf](https://github.com/FlyingDiver/Indigo-radiora2/files/3390020/Lutron.Integration.Protocol.AA.2019-03-12.pdf)

**Comment by FlyingDiver** [comment]
What's interesting is that the document doesn't mention Caséta at all, but it works that that too.
