### ISSUE TITLE
Homeworks QS compatibility

### ISSUE THREAD

**Issue by omrasnake** [FlyingDiver/Indigo-radiora2#36]
hi ,your plugin is amazing , are you  considering implement Homeworks QS in the future ? thanks .

**Comment by FlyingDiver** [comment]
Should work with Homeworks for all devices that work the same using the Integration API.  It's not listed since no one has been able to test it with a Homeworks systems.

**Comment by FlyingDiver** [comment]
If there are Homeworks specific commands that don't work or are missing, then opening an issue for those will be considered, as long as the requestor is willing to take responsibility for all testing.

**Comment by omrasnake** [comment]
thanks for your reactivity , i will test the plugin this week ASAP and share results .

**Comment by omrasnake** [comment]
thanks for your reactivity , i will test the plugin this week ASAP and share results .

**Comment by KardelSniper** [comment]
Hi guys, I’m currently using this awesome plugin with QS, works perfectly, same as RA2. I feel the only minor difference is the integration ID. Seems need to use the zone IDs instead of device IDs, as when the device reports back its status, it always uses the zone ID (these are the zones in the QS software). If device IDs are used then status will never update. In my setup each zone is configured to have a single device so not a problem. Hope this helps! Thanks for the amazing plugin!

**Comment by FlyingDiver** [comment]
> Hi guys, I’m currently using this awesome plugin with QS, works perfectly, same as RA2. I feel the only minor difference is the integration ID. Seems need to use the zone IDs instead of device IDs, as when the device reports back its status, it always uses the zone ID (these are the zones in the QS software). If device IDs are used then status will never update. In my setup each zone is configured to have a single device so not a problem. Hope this helps! Thanks for the amazing plugin!

Can you generate an Integration report or the XML dump for a QS system?  If there's a difference in the nomenclature I might be able to update the plugin to make that more obvious.  I guess I would also need to debug log so I can see the actual messages.  Opening a new issue specifically for that would be best.

**Comment by omrasnake** [comment]
great news ,

**Comment by KardelSniper** [comment]
So with my setup, the integration report is generated in a table format in the QS software on windows (one can probably get this software from their QS installer), so there’s no simple json report (or I don’t know how to get one from QS). And in that table, there are sections for devices and zones. Zones are set up when adding devices into the software, and like I mentioned in my setup each zone corresponds to one device (I think this is what the installer does as a standard). Then when I operate a device - either using indigo or physically, the indigo log shows the received telnet command for status update, it’s the output command, looking like ~OUTPUT, ID, XX, XX, just as the QS telnet integration doc described. It’s just I found that ID is not the device ID, it’s the zone’s ID the device is in. Does this help?

**Comment by FlyingDiver** [comment]
So maybe I just need an update to the Wiki saying use the ZoneID for QS instead of the IntegrationID?

**Comment by omrasnake** [comment]
i have lutron integration designer 10.7 if someone interested .

**Comment by FlyingDiver** [comment]
Have you ever tried to get the XML data from the QS system like you can for the RRA2 system?
````
http://<<IP address>>/login 
http://<<IP address>>/DbXmlInfo.xml
````

**Comment by FlyingDiver** [comment]
> i have lutron integration designer 10.7 if someone interested .

That's the QS programming software?  I use Inclusive for RRA2.

**Comment by omrasnake** [comment]
> > i have lutron integration designer 10.7 if someone interested .
> 
> That's the QS programming software? I use Inclusive for RRA2.

yes its different software difficult to get

**Comment by KardelSniper** [comment]
I tried that XML url, doesn’t work as RA or Caseta, it shows weird stuff not the XML we need, so that’s why I was using the integration report from the software. And it is the Lutron Designer, I’m using v11 as that should be the last version before you need to have an account and sign in. I don’t think you can just download that software online, but I think you need an installer for the QS system anyways so they should be able to help.

**Comment by FlyingDiver** [comment]
OK, I was just wondering if I could extend the device auto-creation I can do for Caseta and RRa2 to QS.  Sounds like a no since I can't get an XML or JSON system config.  Oh well.

**Comment by omrasnake** [comment]
> I tried that XML url, doesn’t work as RA or Caseta, it shows weird stuff not the XML we need, so that’s why I was using the integration report from the software. And it is the Lutron Designer, I’m using v11 as that should be the last version before you need to have an account and sign in. I don’t think you can just download that software online, but I think you need an installer for the QS system anyways so they should be able to help.
check this , can you send me lutron designer v11 pls 
http://www.lutron.com/TechnicalDocumentLibrary/HWQS_XML_Extraction_FAQ.pdf

**Comment by omrasnake** [comment]
> OK, I was just wondering if I could extend the device auto-creation I can do for Caseta and RRa2 to QS. Sounds like a no since I can't get an XML or JSON system config. Oh well.

here linked file https://www.dropbox.com/s/7c387aenu9j2cjl/lutron%20control%20xml%20nov%202014.xml?dl=0

**Comment by FlyingDiver** [comment]
Thanks, I'll take a look.

**Comment by KardelSniper** [comment]
Figured out how to properly get that XML file... Seems like the "zone" I was talking about is called "Outputs" in it

**Comment by FlyingDiver** [comment]
"Output" is the name in all the XML files.  I took a quick look at the submitted XML file, and I think it's probably compatible with the code as is, at least as far as keypads and dimmers/switches are concerned.  So I'm assuming that the auto device creation will work.  If that turns out to be wrong, please open a new issue with the specifics (XML file and plugin log during the creation process).

**Comment by omrasnake** [comment]
i will confirm this week gracias .

**Comment by omrasnake** [comment]
> > i have lutron integration designer 10.7 if someone interested .
> 
> That's the QS programming software? I use Inclusive for RRA2.

can you send me RR inclusive programing soft pls .thanks

**Comment by omrasnake** [comment]
> I tried that XML url, doesn’t work as RA or Caseta, it shows weird stuff not the XML we need, so that’s why I was using the integration report from the software. And it is the Lutron Designer, I’m using v11 as that should be the last version before you need to have an account and sign in. I don’t think you can just download that software online, but I think you need an installer for the QS system anyways so they should be able to help.

please i need lutron V11 designer can you zip it and send it via dropbox ? thanks for your time.

**Comment by FlyingDiver** [comment]
> can you send me RR inclusive programing soft pls .thanks

I can't, it's tied to my Lutron account.  Wouldn't work if you have QS anyway.

**Comment by omrasnake** [comment]
> > can you send me RR inclusive programing soft pls .thanks
> 
> I can't, it's tied to my Lutron account. Wouldn't work if you have QS anyway.

 i have both systems,  RRA essential  is limited to 100 devices ,i need inclusive  but must first certification

**Comment by FlyingDiver** [comment]
It's the same software.  You need to get your Lutron account upgraded to enable Inclusive, or find someone with a dealer type account who can do it for you.

**Comment by FlyingDiver** [comment]
I went to the training class to get certified.

**Comment by omrasnake** [comment]
hi , your plugin is working with Homework QS system , many thanks .
![lutron-lighting-homeworks-qs-hqp6-600](https://user-images.githubusercontent.com/44398695/71641509-8b7e0180-2c9d-11ea-8543-417ab153394a.jpg)
