### ISSUE TITLE
Device creation for RA2 Select bridge integration report does not create any devices

### ISSUE THREAD

**Issue by rspivack** [FlyingDiver/Indigo-radiora2#37]
[lutron integration report ra2 select.txt](https://github.com/FlyingDiver/Indigo-radiora2/files/3823615/lutron.integration.report.ra2.select.txt)

**Comment by FlyingDiver** [comment]
I'm looking at the data you submitted, and have some questions.  What kind of device is your Garage Motion occupancy sensor?  How is that available in the Select programming application?  I need to add support for that, but I'm not sure how to identify it.  Is the "Occupancy Sensor" name fixed, and you just assigned it to an area ("Garage Motion")?

**Comment by rspivack** [comment]
Hi Joe,

 

I have several Lutron LRF2-OWLB-P wall mount occupancy/vacancy sensors, but only one is installed.

 

I’m attaching FAQ and data sheet.

 

There are some limitations:

 

Only work with RA2 Select and higher – doesn’t work with Caseta

 

Like Pico’s, Lutron does not expose them to HomeKit

 

From what I have been able to determine, the sensor is not accessible via Lutron Telnet API so you can’t see motion events and trigger off them.  The only thing you can do is associate a Lutron dimmer/switch to be controlled by the sensor.

 

This makes them fairly limited for custom automations.

 

The reason I started using them is I had so much trouble with the Insteon motion sensors I was using I thought I would give them a try rather than adding Z-wave to my Indigo.  The upside is they are superfast triggering – the light comes on almost instantly and the batteries last much longer.

 

 

Here’s what I have done for automation purposes:

 

I have created a “device proxy” by installing a Lutron dimmer that doesn’t actually control a load.  I have it mounted in a table-top Jbox near my router and other equipment.

 

In the Lutron app I put this dummy device and the occupancy/vacancy sensor in their own dummy room.

 

With automations (I forget whether I did this in Indigo or directly in Apple HomeKit) I mirror the state of the dummy dimmer to the actual target light.  If dummy dimmer goes on, target light goes on, if dummy dimmer goes off, target light goes off, etc.

 

Basically, I use the state of the dummy dimmer as a virtual motion sensor since it is exposed to both Indigo and HomeKit I can build any automations off it I want.

 

The downside is there is now a 1 to 3 second delay.

 

 

The main reason I did this is that I’m using the Lutron motion sensor to control a garage overhead light, but needed a way to have an override to keep it from turning off automatically if I am working in the garage.  By using the proxy device, I can set a variable or another virtual device in Indigo as a “hold” switch to ignore the motion events when I am going to be working in the garage for more than a few minutes.

 

 

If you can find a better way…..

 

 

Last thought – I think that the Lutron sensor might report motion if connected to a Full RA2 main repeater or HomeWorks controller.  I actually also have a RA2 repeater in my home setup, but right now my Caseta and RA2 Select are the “production” ones that are stable so I haven’t tried it with the full RA2.

 

Also, I’m lazy, and hate firing up the Windows VM just to run the damn full Lutron RA2 programming software 😊

 

 

 

 

Robert E. Spivack

Smart Home Technology Specialist

www.DoItForMe.Solutions

robert@doitforme.solutions

 

Office: +1 (408) 647-4687

Cell: +1 (408) 569-5873

**Comment by FlyingDiver** [comment]
Can you turn detailed debug logging on and then trigger the motion sensor?  I want to confirm that it doesn't show up in the log when using a Select (or Caseta) bridge.

**Comment by rspivack** [comment]
Nov 27, 2019 at 12:03:26 PM

   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,5,1,100.00

   Lutron RRA2/Caséta Threaddebug Received an Output message: ~OUTPUT,7,1,100.00

   Lutron RRA2/Caséta Debug       Received: Switch Lights (Garage) turned On

 

 

Nothing ?

**Comment by FlyingDiver** [comment]
Yeah, it would be a ~DEVICE message if it was working like an RRA2 system.  Since the plugin won't get a control message for that device, I'm just going to ignore it.

I've got device creation fixed otherwise.  But it's in my development branch which has a bunch of other things going on.  So it'll be a while before it's released.

**Comment by rspivack** [comment]
Yup, would be nice, but Lutron does what it wants, and tends to ignore input from the more tech oriented.

 

Even as a Lutron Gold Residential Pro dealer I don’t get much sway, but I do like them as they are always very polite, very responsive, and great tech support.

 

 

I’ve got my config working for now, so no rush on the plug-in update.  At some point early 2020 I’ll start moving my home stuff over to my RA2 primary repeater instead of RA2 Select and can check then.

 

 

Thanks!

**Comment by FlyingDiver** [comment]
Oh, the next release will support multiple bridges/repeaters.  So you'll be able to mix-n-match.

**Comment by FlyingDiver** [comment]
Fixed in 7.3.0.
