### ISSUE TITLE
Keypad - multiple presses of a button

### ISSUE THREAD

**Issue by smuseby** [FlyingDiver/Indigo-radiora2#38]
Currently, 3 presses of a button activates the triggers assigned to single, double and triple presses of the button.
I would like the triple press of the button to only execute the trigger assigned to the triple press, and to not execute the triggers assigned to single and double presses.
I have also observed that the double press is not reliable, and am therefore only using single press triggers at the moment.

**Comment by FlyingDiver** [comment]
Can you open a separate issue for the double click problem?  I’ve had no previous reports of that, and I don’t know how triple clicks would work but double would not.

**Comment by FlyingDiver** [comment]
Will be in 7.3.0 release.

**Comment by gt3mike** [comment]
Is this in the current pre-release of 7.3.0?

**Comment by FlyingDiver** [comment]
Yes.  There's two different kinds of button triggers.  You want the "multi press" trigger, I think.  ;)

**Comment by gt3mike** [comment]
Not sure - I'm looking for the multi press where the double press doesn't trigger the single press (and the triple press doesn't trigger the single and double presses). I assume if I upgrade to 7.3.0 I'll need to recreate my existing double press and triple press triggers.

**Comment by FlyingDiver** [comment]
Yeah, that's the newer one.  It's a little fuzzy because I was intending to release this five months ago, forgot, and now I don't remember the details.

**Comment by gt3mike** [comment]
I thought I was the only one that happens to! ;)
