### ISSUE TITLE
Automatically add gateway to existing triggers/actions

### ISSUE THREAD

**Issue by gt3mike** [FlyingDiver/Indigo-radiora2#40]
On upgrade to 7.3, when adding the Gateway property to existing triggers and actions, it would be very helpful to default this property to the first gateway if one exists. Otherwise, some triggers and actions stop working. Finding the null gateway properties and adding a gateway manually is tedious.

**Comment by FlyingDiver** [comment]
Agreed.  I'll see what I can do.  I'm just not sure if I can do anything about them all.

**Comment by FlyingDiver** [comment]
Triggers are updated when loaded.  Need to look at actions.

**Comment by FlyingDiver** [comment]
Actions get the gateway info from the specified device.  No changes needed.
