### ISSUE TITLE
RA2 keypad buttons not updating 

### ISSUE THREAD

**Issue by nevermesswithahornygoat** [FlyingDiver/Indigo-radiora2#45]
If you make changes to an RA2 button device, it won't be recognized or used for triggers until the plugin is reloaded.

**Comment by FlyingDiver** [comment]
What kind of changes did you make?

**Comment by nevermesswithahornygoat** [comment]
Changing the button numbers. Also, IIRC when I was adding buttons, I had to reload for all of them to show up as an option in "Triggers".

**Comment by FlyingDiver** [comment]
OK, I'll look into it.

**Comment by nevermesswithahornygoat** [comment]
Forgot to add that the command looks good in the log, just nothing gets triggered on the Indigo side.

**Comment by nevermesswithahornygoat** [comment]
Also had this communication issue happen twice in a week. Reloading the plugin fixes it. 

```
   Lutron RRA2/Caséta Debug       Received a keypad button/LED status message: ~DEVICE,17,11,3
   Lutron RRA2/Caséta Debug       buttonTriggerCheck: deviceID: 17, componentID: 11, gatewayID: 1250373267
   Lutron RRA2/Caséta Debug       buttonTriggerCheck: Executing Trigger 'Theater Tabletop Shade button 11', keypad button: 
   Trigger                         Theater Tabletop Shade button 11
   Lutron RRA2/Caséta Debug       Caseta Hub: Sending command: '#DEVICE,36,8,4'
   Lutron RRA2/Caséta Warning     Caseta Hub: Error sending IP command, resetting connection:  'int' object has no attribute 'sendall'

```

**Comment by FlyingDiver** [comment]
Something is stepping on the connection object.  I'll need to look into that as well.

Also, turn down the debugging one level.  Detailed Debugging is overkill most of the time.

**Comment by nevermesswithahornygoat** [comment]
Here's a new error message after it was running fine for a few days: 

 ```
Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 1049, in runConcurrentThread
  File "plugin.py", line 154, in poll
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/telnetlib.py", line 430, in read_eager
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/telnetlib.py", line 576, in fill_rawq
error: [Errno 60] Operation timed out

   Lutron RRA2/Caséta Error       plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

```

**Comment by FlyingDiver** [comment]
Looks like a network error of some kind.  I need to catch that error, I guess.

**Comment by nevermesswithahornygoat** [comment]
Yea, it's pretty strange. Reloading the plugin fixes the issue. 

Indigo is the the only thing actively running on a new i5 mac mini connected directly to the switch. Router is eero pro.

**Comment by FlyingDiver** [comment]
Added code to trap for the time out error.

I think I know what's going on with the button editing.  Working on a fix now.

**Comment by FlyingDiver** [comment]
Fix will be in next release.
