### ISSUE TITLE
Battery status?

### ISSUE THREAD

**Issue by FlyingDiver** [FlyingDiver/Indigo-radiora2#46]
https://forums.indigodomo.com/viewtopic.php?f=217&t=24475

> I have several groups of Serena shades working with the plugin. I also have a remote. (So at this point, all my Lutron devices are battery powered.)
> 
> I noticed in the release notes for a recent update of the Lutron IOS App that it mentions "Caseta and RA2 Select now have Low Battery Alerts in the app. Be alerted if your battery runs low for Picos, Shades, and Occupancy Sensors!". 
> 
> So if the app can do this, is it possible for the plugin to do it as well? Ideally, I'd love to see the battery state of Lutron devices from within Indigo. Or at least to be able to attach a trigger to a low-battery warning event.

**Comment by FlyingDiver** [comment]
<img width="799" alt="Screen Shot 2020-10-22 at 4 16 03 PM" src="https://user-images.githubusercontent.com/72976/96925309-f3e2dd00-1481-11eb-82fd-f0d9fb75ef0b.png">

**Comment by gt3mike** [comment]
Looking forward to seeing whether this works in RR2 and not just RR2 Select!

**Comment by FlyingDiver** [comment]
I'm going to need some testers, since I don't have any battery shades.

**Comment by gt3mike** [comment]
Me either. But I have plenty of Picos and sensors.

**Comment by rapamatic** [comment]
It seemed to work for me. I have a battery powered roller that is device ID 18, here is what I got back when I sent a battery request command. I don't understand the date in the return string, especially since the integration ID 18 is one I've had longer than integration ID 60. 

```
Oct 22, 2020 at 3:55:19 PM
   Action Group                    Shade status test
   Lutron RRA2/Caséta Debug       Lutron Main Repeater #1 Downstairs: Sending command: '?DEVICE, 18, 1, 22'
   Lutron RRA2/Caséta Debug       Sent Raw Command: '?DEVICE, 18, 1, 22' to gateway 402305932
   Lutron RRA2/Caséta Threaddebug Lutron Main Repeater #1 Downstairs: 50 characters read:
~DEVICE,18,1,22,0x011E0AE1,1,1,06/16/2019 14:18:38
   Lutron RRA2/Caséta Threaddebug Lutron Main Repeater #1 Downstairs: 9 characters read:
 
GNET> 
   Lutron RRA2/Caséta Threaddebug Lutron Main Repeater #1 Downstairs: self.buffer = 'GNET> ~DEVICE,18,1,22,0x011E0AE1,1,1,06/16/2019 14:18:38 
GNET> '
   Lutron RRA2/Caséta Threaddebug Lutron Main Repeater #1 Downstairs: msg = 'GNET> ~DEVICE,18,1,22,0x011E0AE1,1,1,06/16/2019 14:18:38 
'
   Lutron RRA2/Caséta Threaddebug Lutron Main Repeater #1 Downstairs: self.buffer = 'GNET> '
   Lutron RRA2/Caséta Threaddebug Received command: GNET> ~DEVICE,18,1,22,0x011E0AE1,1,1,06/16/2019 14:18:38 from Gateway 402305932
   Lutron RRA2/Caséta Threaddebug Received a Device message: GNET> ~DEVICE,18,1,22,0x011E0AE1,1,1,06/16/2019 14:18:38

```

And here is from sending the command to a different battery shade:

```
Action Group                    Shade status test
   Lutron RRA2/Caséta Debug       Lutron Main Repeater #1 Downstairs: Sending command: '?DEVICE, 60, 1, 22'
   Lutron RRA2/Caséta Debug       Sent Raw Command: '?DEVICE, 60, 1, 22' to gateway 402305932
   Lutron RRA2/Caséta Threaddebug Lutron Main Repeater #1 Downstairs: 50 characters read:
~DEVICE,60,1,22,0x011E2A64,1,1,04/24/2016 14:51:30
   Lutron RRA2/Caséta Threaddebug Lutron Main Repeater #1 Downstairs: 9 characters read:
 
GNET> 
   Lutron RRA2/Caséta Threaddebug Lutron Main Repeater #1 Downstairs: self.buffer = 'GNET> ~DEVICE,60,1,22,0x011E2A64,1,1,04/24/2016 14:51:30 
GNET> '
   Lutron RRA2/Caséta Threaddebug Lutron Main Repeater #1 Downstairs: msg = 'GNET> ~DEVICE,60,1,22,0x011E2A64,1,1,04/24/2016 14:51:30 
'
   Lutron RRA2/Caséta Threaddebug Lutron Main Repeater #1 Downstairs: self.buffer = 'GNET> '
   Lutron RRA2/Caséta Threaddebug Received command: GNET> ~DEVICE,60,1,22,0x011E2A64,1,1,04/24/2016 14:51:30 from Gateway 402305932
   Lutron RRA2/Caséta Threaddebug Received a Device message: GNET> ~DEVICE,60,1,22,0x011E2A64,1,1,04/24/2016 14:51:30
```

**Comment by FlyingDiver** [comment]
Any chance those are the dates you last changed the batteries?

**Comment by FlyingDiver** [comment]
I'm trying to figure out where in that string is the battery status.

`~DEVICE,18,1,22,0x011E0AE1,1,1,06/16/2019 14:18:38`

**Comment by rapamatic** [comment]
It is conceivable, depending on how carefully they calculate that - we recently repainted the room that the integration ID 18 shade is in, and the batteries were out of the shade for a few days. I put the same ones back in, so maybe it didn't detect that as a change...

I honestly don't remember when I last changed batteries - the shades are pretty incredible in that regard.

**Comment by FlyingDiver** [comment]
I'm just thinking that they might remember when they last lost power, which could be a change indicator.

**Comment by rapamatic** [comment]
Thinking about it more, that could be the last date that the battery status changed (e.g. from low state to normal state...)... because since I just took out the batteries when I repainted the room and put them back in, the shades would not have registered a low charge state....

**Comment by FlyingDiver** [comment]
Well, it's gotta be one of the two fields immediately after the device address.  Hmmm.

**Comment by FlyingDiver** [comment]
Ah.  This page is for the temperature sensors (for the HVAC controller), but I bet it's the same data.

<img width="763" alt="Screen Shot 2020-10-22 at 5 43 37 PM" src="https://user-images.githubusercontent.com/72976/96933295-30b4d100-148e-11eb-8abc-6ecd31c9779b.png">

**Comment by rapamatic** [comment]
> I'm trying to figure out where in that string is the battery status.
> 
> `~DEVICE,18,1,22,0x011E0AE1,1,1,06/16/2019 14:18:38`

Yeah, it is tricky since they don't document this function... If I had some spare almost dead D-cells I could try swapping them out... or maybe removing one battery? I don't know what the voltage is that triggers a low voltage state...

**Comment by rapamatic** [comment]
Ah, I should have thought to look at the wireless temp sensor response. That makes sense. So like I guessed, the date is the last time the status changed...

**Comment by FlyingDiver** [comment]
Here's the result for a hardwired shade:
`~DEVICE,128,1,22,0x00BB13B1,2,1,01/01/2000 00:00:00`

**Comment by FlyingDiver** [comment]
So, yeah, I can do something with that.

**Comment by rapamatic** [comment]
I can confirm that I get the same response from a hardwired shade

`~DEVICE,128,1,22,0x01EE87EB,2,1,01/01/2000 00:00:00 `

**Comment by rapamatic** [comment]
I wonder what the point is of the hex number in the response?

**Comment by FlyingDiver** [comment]
I think that's the MAC/HW Serial number of the device.

**Comment by gt3mike** [comment]
Do you think this will work for Picos and sensors too, or just shades?

**Comment by FlyingDiver** [comment]
I just tested the query command with both a motion sensor and a Pico, and got the same kind of results back.  So yeah, probably will work.

**Comment by FlyingDiver** [comment]
Since I'll have to specifically poll for this data, how should I schedule that?

**Comment by FlyingDiver** [comment]
Test version available:  https://github.com/FlyingDiver/Indigo-radiora2/releases/tag/7.4.0

I punted on the scheduling of the update, and made an Action that does it.  So just use the Indigo scheduler to update the battery levels as you want.

**Comment by rapamatic** [comment]
That makes sense. I’ll test tomorrow.

**Comment by FlyingDiver** [comment]
Note that it polls all the possible battery devices (Picos, Sensors, Shades) and adds the battery level property to each that reply that they're using battery.  So they show in the UI.

Weird note is that I have to do each Pico button individually, so they all show that UI.  At some point it might make sense to go back and create device groups for keypads to group the buttons.  I think that can be done without breaking back compatibility.  I need to try that to see.

**Comment by gt3mike** [comment]
Any idea whether this is dependent on any particular RR2 firmware version?

**Comment by FlyingDiver** [comment]
It probably is, but I have no idea how to tell which ones.  That would require digging through the release notes.

**Comment by FlyingDiver** [comment]
All the testing I'm doing is showing that this is working properly, and @rapamatic is seeing the same results.  I'm going to let this bake for another day or two before releasing.  I'm going to take a look at the other open issues before I do.

**Comment by FlyingDiver** [comment]
Release 7.4.0.  Updated store.
