### ISSUE TITLE
String to Float error in logs

### ISSUE THREAD

**Issue by mlamoure** [FlyingDiver/Indigo-radiora2#5]
I occasionally find this in my logs.  It does not seem to be blocking any functionality.

Lutron RRA2/Caséta Error       Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 366, in runConcurrentThread
  File "plugin.py", line 530, in _processCommand
  File "plugin.py", line 568, in _cmdOutputChange
ValueError: could not convert string to float: GNET> 0.00

   Lutron RRA2/Caséta Error       plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

**Comment by mlamoure** [comment]
FlyingDiver,

I've self-fixed this error which seems to be stable for me for the past 10+ days.  I'm not exactly sure **why** a non numeric value would be sent through the _cmdOutputChange function, but based on the error in the indigo log, that's what I assumed was happening and so I adjusted to meet this condition.  Let me know what you think.

I added to the _cmdOutputChange function after the level variable is assigned a check for the value:

```
            if not self.is_number(level):
                return
```
and my definition of is_number:

```
    def is_number(self, s):
        try:
            float(s)
            return True
        except ValueError:
            return False  

```

**Comment by FlyingDiver** [comment]
I implemented a slightly different fix in 7.0.3, which is marked pre-release.  Can you test?

**Comment by mlamoure** [comment]
Yes, installed it and will let you know.  Thanks!

**Comment by mlamoure** [comment]
Very stable so far.  Thanks again for the plugin.

**Comment by FlyingDiver** [comment]
Releasing 7.0.3.
