### ISSUE TITLE
Caseta weirdness

### ISSUE THREAD

**Issue by docbjr** [FlyingDiver/Indigo-radiora2#50]
All of a sudden, my Pico PJ2-4B (4 button) started acting strange today. It was programed so that each button caused an event to take place. (I do have a Bridge Pro)

Now when I push a button, I see the state of the button turn on in Indigo, but it turns off immediately. All 4 buttons act this way. However, I can activate the devices with Indigo.

I'm not sure I've made this clear.
Thanks

**Comment by docbjr** [comment]
Debugging shows this when I push a button:
Lutron RRA2/Caséta Debug Received a pico button status message: GNET> ~DEVICE,4,8,3
Lutron RRA2/Caséta Debug buttonTriggerCheck: deviceID: 4, componentID: 8, gatewayID: 645502356
Lutron RRA2/Caséta Debug Received a pico button status message: ~DEVICE,4,8,4
Lutron RRA2/Caséta Debug buttonMultiPressCheck: Timeout reached for keypadid = 645502356:4.8, presses = 1

**Comment by FlyingDiver** [comment]
Why did you close it?

**Comment by docbjr** [comment]
Actually, I can not activate the devices with Indigo even though Indigo shows that the device is on.

**Comment by FlyingDiver** [comment]
What device are you talking about?  The Pico, or the one it was supposed to control?  You can't activate a Pico button.

It looks like maybe your triggers got turned off.  Check that they all enabled, and maybe post a screenshot of one of them that's not working.

**Comment by docbjr** [comment]
A mistake…I’ve never used GitHub before. Sorry.

**Comment by docbjr** [comment]
Apparently the triggers did indeed get turned off. I have re-created one so far and it works.

I wonder what happened, but thanks for your help.
