### ISSUE TITLE
Lutron Button 7 LED Device and Indigo Trigger

### ISSUE THREAD

**Issue by smuseby** [FlyingDiver/Indigo-radiora2#59]
Creating an LED device (87) causes it to appear along with the device (7) in the list of possible triggers (when creating a trigger).

**Comment by FlyingDiver** [comment]
This is a bug in the manual device creation definition.  All manually created LED devices are marked as buttons.

**Comment by FlyingDiver** [comment]
Fixed in 2022.1.1
