### ISSUE TITLE
Plugin fails to start if configured for serial gateway

### ISSUE THREAD

**Issue by RatRanch** [FlyingDiver/Indigo-radiora2#62]
Plugin throws this error:

     Lutron RRA2/Caséta Error	exception in device_start_comm(Lutron Serial Gateway): 'SerialGateway' object has no attribute 'dev'

**Comment by FlyingDiver** [comment]
OOps.

**Comment by FlyingDiver** [comment]
Pre-release committed.  I'll push a final release later in the week after testing.

**Comment by FlyingDiver** [comment]
Released to plugin store.
