### ISSUE TITLE
Choose from device list when setting triggers on keypad buttons

### ISSUE THREAD

**Issue by gt3mike** [FlyingDiver/Indigo-radiora2#7]
It appears that an Indigo Device needs to exist for a keypad button if an Indigo Trigger is going to be set up to trigger based on that button being pressed. If this is always the case, it would make sense to choose that Indigo Device from a dropdown during Trigger creation, rather than asking for the device ID and component ID as is currently the case.  
![trigger](https://user-images.githubusercontent.com/35278984/34787317-13ea7734-f5f4-11e7-80ce-ac03b69e01df.png)

**Comment by FlyingDiver** [comment]
Good point.  I think all that code predates me working on this plugin, but I'll take a look as see if there's a way to handle this without breaking existing installs.

**Comment by FlyingDiver** [comment]
I'm working on improvements that will use pop-up device lists everywhere, except manual device creation.  That way if you use the auto-create function you'll never need to enter device and component IDs.

**Comment by rapamatic** [comment]
Damn - you're making it too easy for the new folks to use the plugin - I liked it the old fashioned way when we had to code everything uphill both ways :)

**Comment by gt3mike** [comment]
Excellent!!

**Comment by FlyingDiver** [comment]
In 7.1.0-b7
